### ISSUE TITLE
[RFE] Data in yaml is not modeled exactly as specified by the API

### ISSUE THREAD

**Issue by enothen** [enothen/ansible-image-builder#47]
Take for example this definition:
```
  - name: rhel-9-aarch64-ib
    upload_type: aws
    upload_options:
      share_with_sources:
        - "123456"
    compose:
      architecture: aarch64
      distribution: rhel-9
      image_description: RHEL 9.latest aarch64 image shared with an AWS account
      image_type: aws
      customizations:
        filesystems:
          - mountpoint: /
            min_size: 10240
          - mountpoint: /tmp
            min_size: 1024
        packages:
            - jq
            - sysstat
```
The architecture and distribution parameters are both keys at the root of the dictionary, but looking at the [API definition](https://developers.redhat.com/api-catalog/api/image-builder#schema-ComposeRequest), some errors are evident. Eg: architecture belongs to the `ImageRequest` object and distribution belongs to the `ComposeRequest` object.
A proper structure in yaml that would represent the API accurately would be:
```
images:
  - name: rhel-9-aarch64-ib
    description: RHEL 9.latest aarch64 image shared with an AWS account
    distribution: rhel-9
    customizations:
      filesystems:
        - mountpoint: /
          min_size: 10240
        - mountpoint: /tmp
          min_size: 1024
      packages:
        - jq
        - sysstat
    requests:
      architecture: aarch64
      image_type: aws
      size: 53687091200
      upload_request:
        type: aws
        options:
          share_with_sources:
            - "123456"
```
Implementing this change will of course break all existing playbooks and image definitions, but it will be easier to understand just looking at yaml "what belongs where". Additionally, it might avoid some issues with native data types.
