### ISSUE TITLE
[RFE] Allow for other image formats

### ISSUE THREAD

**Issue by enothen** [enothen/ansible-image-builder#7]
Qcow2 is the hardcoded image format in the templates as of right now. Making it part of the image definition would allow to specify other image formats supported by Image Builder, such as .ova or .vmdk

**Comment by benblasco** [comment]
AMI work has already been done here and could be used to accelerate this for AWS.

https://gitlab.consulting.redhat.com/biholmes/image-builder-poc

**Comment by enothen** [comment]
AWS as target environment is working, for example like this:
```
images:
  - name: rhel-9-awstest-enothen-ib
    upload_type: aws
    upload_options:
      share_with_sources:
        - "123456"
    compose:
      distribution: rhel-9
      image_description: RHEL 9.2 base
      image_type: aws
      customizations:
        filesystem: "{{ filesystems.base }}"
        packages: "{{ packages.base }}"
```
Will add this to the examples.
